// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmYxomNGGrE-ZBqCmT2Lb68_ZKCnxeBU',
    appId: '1:14861479788:web:328bd93fcc3bbf92d7cd49',
    messagingSenderId: '14861479788',
    projectId: 'siirler-84b54',
    authDomain: 'siirler-84b54.firebaseapp.com',
    storageBucket: 'siirler-84b54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6dhcp1qw762VyCtHcV1nDO8jAGLXGruA',
    appId: '1:14861479788:android:d7729ad528b85181d7cd49',
    messagingSenderId: '14861479788',
    projectId: 'siirler-84b54',
    storageBucket: 'siirler-84b54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnL68Hu8nN4VZwoDB6DwKlYO1lOVhHYw',
    appId: '1:14861479788:ios:c871df9610c5fdeed7cd49',
    messagingSenderId: '14861479788',
    projectId: 'siirler-84b54',
    storageBucket: 'siirler-84b54.appspot.com',
    iosClientId: '14861479788-ukt8lheak2um1pjoavjt4nqnfb9ui99r.apps.googleusercontent.com',
    iosBundleId: 'com.siirbu.siirler',
  );
}
